# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :development do
  gem "rake", "~> 12.3.0"
  gem "rdoc", "~> 6.0"
  gem "travis", "~> 1.8"
end

group :test do
  gem "aruba", "~> 0.14.6"
  gem "cucumber", "~> 3.1"
end

