require 'cucumber'
require 'cucumber/rake/task'

console_runner_class_dir = File.join File.dirname(__FILE__), 'console-runner/build/classes/java/main'
features_dir = File.join File.dirname(__FILE__), 'features'

desc 'Compile, run all tests, and run checkstyle'
task default: %w[java:test cucumber checkstyle:run]

namespace :checkstyle do #TODO KDK: Move to gradle check task
  filename = 'checkstyle-8.18-all.jar'
  local_path = "checkstyle/#{filename}"

  desc 'Download Checkstyle'
  task :download do
    next if File.exists? local_path
    sh *%W[curl -Ls https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.18/#{filename} -o #{local_path}]
  end

  desc 'Perform static analysis on Java code'
  task :run => :download do
    # http://checkstyle.sourceforge.net/cmdline.html#Download_and_Run
    sh *%W[java -jar #{local_path} -c ./checkstyle-main.xml console-runner/src/main/java lambda-api/src/main/java]
    sh *%W[java -jar #{local_path} -c ./checkstyle-test.xml console-runner/src/test/java console-runner-features/src/test/java lambda-api/src/test/java]
  end
end


desc 'Clean everything'
task :clean => 'java:clean'


Cucumber::Rake::Task.new do |task|
  task.cucumber_opts = %w[
    --quiet
    --strict
    --tags 'not @wip'
  ]
end

namespace :cucumber do
  desc 'Run Cucumber scenarios tagged with @focus'
  task :focus do
    sh *%w[cucumber -t @focus]
  end
end


namespace :java do
  desc 'Remove everything generated and compiled from Java code'
  task :clean do
    gradle %w[--stacktrace clean]
  end

  desc 'Compile Java sources'
  task :compile do
    gradle %w[--stacktrace build -x test]
  end

  desc 'Open cucumber-jvm report'
  task 'cucumber-report' do
    sh *%w[open console-runner-features/build/reports/cucumber/index.html]
  end

  desc 'Run all tests on Java code'
  task :test do
    #Cucumber options: https://github.com/cucumber/cucumber-java-skeleton#overriding-options
    gradle %w[--stacktrace build]
  end

  def gradle(tasks)
    gradle_command =
      # https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
      if ENV['CI']
        %w[./gradlew --console=plain]
      else
        %w[./gradlew]
      end

    sh *gradle_command + tasks
  end
end


namespace :jetbrains do
  desc 'Remove all project files from Jetbrains IDEs'
  task :reset do
    sh *%w[rm -Rf .idea]
    sh "find . -iname '*.iml' -print -exec rm -Rf {} +"
  end
end


namespace :travis do
  desc 'Run the linter on the Travis configuration'
  task :lint do
    sh *%w[travis lint]
  end
end
