#This file is NOT reloaded automatically when using `bundle exec jekyll serve`.
#If you change this file, please restart the server process.

#Site settings, e.g. {{ site.title }}, etc...
baseurl: "" #subpath of your site, e.g. /blog
description: >-
  JavaSpec 2.x is a Java library that lets you use lambdas to write
  specifications that run on the JUnit 5 platform.
github_username: kkrull
title: JavaSpec 2.0
url: "https://javaspec.info" #protocol + base hostname, e.g. http://example.com
twitter_username: KrullKyle

#Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

#Files to exclude from processing
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

## just-the-docs

aux_links:
  "GitHub Repository":
  - "//github.com/kkrull/javaspec"
aux_links_new_tab: true
