#This file is NOT reloaded automatically when using `bundle exec jekyll serve`.
#If you change this file, please restart the server process.

#Site settings, e.g. {{ site.title }}, etc...
baseurl: "" #subpath of your site, e.g. /blog
description: >-
  JavaSpec 2.x is a Java library that lets you use lambdas to write
  specifications that run on the JUnit 5 platform.
github_username: kkrull
title: JavaSpec 2.0
url: "https://javaspec.info" #protocol + base hostname, e.g. http://example.com
twitter_username: KrullKyle

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-feed
- jekyll-remote-theme # add this line to the plugins list if you already have one

#Files to exclude from processing
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
