source "https://rubygems.org"

#Omit `jekyll` in favor of `github-pages`, when deploying to GitHub Pages
#gem "jekyll", "~> 4.3.2"
gem "github-pages", "~> 228", group: :jekyll_plugins
gem "webrick", "~> 1.8"

#Jekyll theme

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem 'jekyll-theme-leap-day', '~> 0.2.0'
end

## Platform-specific

#Bundle timezone information, for platforms that do not do so naturally
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

#Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

#Lock http_parser version on JRuby, since newer versions lack a Java counterpart
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
