#!/bin/sh

# Redirect output to stderr.
exec 1>&2

checkCodeFormat() {
  local project_directory="$1"
  echo "[$0] Checking code format: $project_directory"
  pushd . > /dev/null
  cd "$project_directory"
  ./gradlew -q spotlessCheck
  popd > /dev/null
}

checkCodeFormat 'examples'
checkCodeFormat 'nested-lambdas'
