name: Pull Request Create/Update

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK and Gradle
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: 'adopt'
          java-version: '11'

      - name: Make scripts executable
        working-directory: './nested-lambdas'
        run: chmod +x gradlew

      - name: Build
        working-directory: './nested-lambdas'
        run: ./gradlew build
